"""empty message

Revision ID: 1b316d3fb45b
Revises: 
Create Date: 2024-03-22 13:09:01.811714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b316d3fb45b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_well_number', sa.Integer(), nullable=True),
    sa.Column('oil', sa.Integer(), nullable=True),
    sa.Column('gas', sa.Integer(), nullable=True),
    sa.Column('brine', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_well_number')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_id'))

    op.drop_table('organization')
    # ### end Alembic commands ###
